###
@BASE_URL = http://localhost
@AUTH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNyaXN0b3BoZXIuY2hhdmFycmlhIiwiaWF0IjoxNzcyODMwMTY0LCJleHAiOjE3NzI4MzA3NjR9.IpmWVe7lzoBL4GQpsr61A2jBm3YCL9tn6miHiXjbmR0


### --- AUTENTICAR ---
### Valida credenciales y retorna un token JWT
POST {{ BASE_URL }}/usuarios/autenticar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "username": "cristopher.chavarria",
  "password_hash": "bcrypt_hash_simulado"
}

### --- VALIDAR TOKEN ---
### Valida el token enviado en la cabecera de autorización.
### El resultado es un objeto con la información del usuario asociado al token.
POST {{ BASE_URL }}/usuarios/validarToken HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "username": "cristopher.chavarria",
  "password_hash": "bcrypt_hash_simulado"
}


### --- DESAUTENTICAR ---
### Borra el token del usuario en la base de datos
POST {{ BASE_URL }}/usuarios/desautenticar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "username": "cristopher.chavarria"
}

### --- USUARIOS ---
### Listar
GET {{ BASE_URL }}/usuarios/usuarioslistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Lista un usuario específico segun el parametro enviado en el body de la solicitud. 
POST {{ BASE_URL }}/Usuarios/usuarioslistarEspecifico HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "username": "cristopher.chavarria"
}

### Crear
POST {{ BASE_URL }}/usuarios/usuarioscrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "username": "usuario.prueba5",
    "password_hash": "bcrypt_hash_simulado",
    "rol": "Empleado",
    "empleado_id": 105,
    "estado": 1,
    "pregunta_seguridad": "¿Color favorito?",
    "respuesta_seguridad": "Verde"
}

### Actualizar
PUT {{ BASE_URL }}/usuarios/usuariosactualizar/78 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "username": "usuario.prueba",
    "rol": "Administrador",
    "empleado_id": 101,
    "estado": 1,
    "pregunta_seguridad": "¿Color favorito?",
    "respuesta_seguridad": "Negro"
}

### Eliminar
DELETE {{ BASE_URL }}/usuarios/usuarioseliminar/78 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}


### --- EMPLEADOS ---
### Listar
GET {{ BASE_URL }}/empleados/empleadoslistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

### Crear
POST {{ BASE_URL }}/empleados/empleadoscrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "codigo_empleado": "EMP-2026123",
    "nombre": "David",
    "apellido": "Chavarria",
    "dni": "2-0123-0033",
    "fecha_ingreso": "2026-02-06",
    "salario_base": 2050000,
    "puesto_id": 2,
    "horario_id": 1
}

### Actualizar
PUT {{ BASE_URL }}/empleados/empleadosactualizar/104 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "codigo_empleado": "EMP-2026123",
    "nombre": "Cristopher",
    "apellido": "Alvarez",
    "dni": "2-0123-0033",
    "fecha_ingreso": "2026-02-06",
    "salario_base": 2050000,
    "puesto_id": 2,
    "horario_id": 1
}

### Eliminar
DELETE {{ BASE_URL }}/empleados/empleadoseliminar/103 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}


### --- DEPARTAMENTOS ---
### Listar
GET {{ BASE_URL }}/departamentos/departamentoslistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Crear
POST {{ BASE_URL }}/departamentos/departamentoscrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Recursos Humanos Explotacion"
}

### Actualizar
PUT {{ BASE_URL }}/departamentos/departamentosactualizar/21 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Talento Humano Prueba"
}

### Eliminar
DELETE {{ BASE_URL }}/departamentos/departamentoseliminar/21 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}


### --- PUESTOS ---
### Listar
GET {{ BASE_URL }}/puestos/puestoslistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Crear
POST {{ BASE_URL }}/puestos/puestoscrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Analista Junior",
    "salario_base_sugerido": 1250000,
    "departamento_id": 1
}

### Actualizar
PUT {{ BASE_URL }}/puestos/puestosactualizar/16 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Analista Junior Process",
    "salario_base_sugerido": 1350000,
    "departamento_id": 1
}

### Eliminar
DELETE {{ BASE_URL }}/puestos/puestoseliminar/16 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}


### --- MOVIMIENTOS ---
### Listar
GET {{ BASE_URL }}/movimientos_planilla/movimientos_planillalistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Crear
POST {{ BASE_URL }}/movimientos_planilla/movimientos_planillacrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "empleado_id": 101,
    "periodo_id": 1,
    "concepto_id": 3,
    "monto_calculado": 15000.50
}

### Eliminar
DELETE {{ BASE_URL }}/movimientos_planilla/movimientos_planillaeliminar/101 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}


### --- PERIODOS ---
### Listar
GET {{ BASE_URL }}/periodos_planilla/periodos_planillalistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Crear
POST {{ BASE_URL }}/periodos_planilla/periodos_planillacrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre_periodo": "Febrero 2026",
    "fecha_inicio": "2026-02-01",
    "fecha_fin": "2026-02-28",
    "estado": "Abierto"
}

### Actualizar
PUT {{ BASE_URL }}/periodos_planilla/periodos_planillaactualizar/1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre_periodo": "Enero 2026 Editado",
    "fecha_inicio": "2026-01-01",
    "fecha_fin": "2026-01-31",
    "estado": "Cerrado"
}

### --- CONCEPTOS ---
### Listar
GET {{ BASE_URL }}/concepto/conceptoslistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Crear
POST {{ BASE_URL }}/concepto/conceptoscrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Bono Nocturno",
    "tipo": "Ingreso",
    "es_ley": 1
}

### Actualizar
PUT {{ BASE_URL }}/concepto/conceptosactualizar/21 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Bono Nocturno Especial",
    "tipo": "Ingreso",
    "es_ley": 1
}

### Eliminar
DELETE {{ BASE_URL }}/concepto/conceptoseliminar/21 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}



### --- AUDITORÍA ---
### Listar
GET {{ BASE_URL }}/auditoria/auditorialistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Agregar registro de auditoría
POST {{ BASE_URL }}/auditoria/auditoriacrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
  "usuario_id": 23,
  "tabla_afectada": "conceptos",
  "registro_id": 21,
  "accion": "UPDATE",
  "valor_anterior": {
    "nombre": "Bono Nocturno Especial"
  },
  "valor_nuevo": {
    "nombre": "Bono Nocturno Especial Editado"
  }
}


### --- HORARIOS ---
### Listar
GET {{ BASE_URL }}/horarios/horarioslistar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}

### Crear
POST {{ BASE_URL }}/horarios/horarioscrear HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Jornada de Fin de Semana",
    "hora_entrada": "08:00:00",
    "hora_salida": "17:00:00",
    "dias_laborables": "S-D"
}

### Actualizar
PUT {{ BASE_URL }}/horarios/horariosactualizar/5 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json

{
    "nombre": "Jornada Fin de Semana Modificada",
    "hora_entrada": "07:00:00",
    "hora_salida": "16:00:00",
    "dias_laborables": "S-D"
}

### Eliminar
DELETE {{ BASE_URL }}/horarios/horarioseliminar/5 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
